### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by kennyparsons** [rail5/SimpleFS#1] opened 2020-12-28 20:01 UTC
@rail5 I'm having some trouble logging in. I've created user via setup.php, and veirfy that config.global.php has the username and hashed password of the user I created. But upon attempting to log in, I get no errors or messages of any kind. It just loops me back to the login page. 

What do you need to troubleshoot?

**Comment by rail5** [comment] 2020-12-28 23:19
Well, the script _login.php_ is structured such that if the form has been submitted, it will always either 1. establish the PHP session, and redirect to _manage.php_ or 2. display an error. In turn, _manage.php_ is configured to check the PHP session variable, and if it is unset, redirect back to _login.php_

So a few things are possible, and I'm going to ask you to check since I haven't been able to reproduce this bug myself:

_1. The form is not being properly submitted_
To check this, open the Network tab in Firefox (Ctrl+Shift+K or Command+Option+K) before submitting the form; after submitting, you should see a request listed with method "POST."
If so, this isn't the issue. If not, it could be a browser bug

_2. (Substantially more likely, my best guess) The PHP Session isn't being written properly_
This would be most likely because the session directory (probably /tmp/) on your server isn't writable -- check by running this script on your server:
`<?php
if (!is_writable(session_save_path())) {
    echo 'Session path "'.session_save_path().'" is <b>not writable</b> for PHP'; 
} else {
    echo 'Session path "'.session_save_path().'" <b>is</b> writable for PHP';
}
?>`
If it displays that your session path is not writable, this can be fixed easily enough:
`$ chmod -R 1777 /tmp/`
Where **/tmp/** should be replaced with your session path, if it happened to be something else

_3. The errors are displaying for an incorrect username or password, but for some reason aren't being formatted properly in the browser so as to be less visible or invisible_
To check this, after trying to sign in and finding yourself looped back to login.php, just view-source and see if you can spot "Invalid username or password"

Let me know what you find, hope we can get this up and running for you.

**Comment by kennyparsons** [comment] 2020-12-29 02:21
1. I see a POST in the network tab.
2. Session folder is writtable, and I see an active session in the folder. Permissions are set for www-data on all directories for php-fpm (nginx is my webserver, of choice, btw). 
3. No mention of invalid username or password in the source after a login loop.
4. manage.php redirects me to login.

**Comment by rail5** [comment] 2020-12-29 02:37
>     2. Session folder is writtable, and I see an active session in the folder. Permissions are set for www-data on all directories for php-fpm (nginx is my webserver, of choice, btw).

I see, check:

`$ ps -ef | grep nginx`

And see if the process is owned by www-data or by the "nginx" user.

Regardless, it's probably a good idea to set permissions for nginx _as well as_ www-data on those directories

Check your active php.ini as well to verify the session directory - some installations point to /var/lib/php/session instead of /tmp/

If _manage.php_ is redirecting you to the login page, it's because it can't find the $_SESSION['valid'] variable supposed to have been set by _login.php_ -- so we've pinpointed the region of the problem, hopefully it's as simple as setting permissions for the nginx user

**Comment by kennyparsons** [comment] 2020-12-29 02:42
> ps -ef | grep nginx
```bash
root@dal-prod-hosting01:~# ps -ef | grep nginx
root      1590     1  0 Dec08 ?        00:00:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
nginx    10272  1590  0 13:52 ?        00:00:00 nginx: worker process
nginx    10273  1590  0 13:52 ?        00:00:00 nginx: worker process
root     21732 21651  0 20:40 pts/0    00:00:00 grep nginx
```

My session path is `/var/lib/php/sessions` with an "s"

**Comment by rail5** [comment] 2020-12-29 02:43
So it's owned by nginx rather than www-data, run:
`$ chown -R nginx:nginx /var/lib/php/sessions/`

**Comment by kennyparsons** [comment] 2020-12-29 02:45
> chown -R nginx:nginx /var/lib/php/sessions/
Would this cause php issues, as it no longer has permissions to its own session folder?

**Comment by rail5** [comment] 2020-12-29 02:47
> > chown -R nginx:nginx /var/lib/php/sessions/
> 
> Would this cause php issues, as it no longer has permissions to its own session folder?

On second thought, it's much better practice to add nginx to the apache group instead of messing with php's permissions

Give this a shot:

`$ adduser nginx apache`

**Comment by kennyparsons** [comment] 2020-12-29 02:48
I don't have apache. So that group doesn't exist.

**Comment by rail5** [comment] 2020-12-29 02:51
Well, you have www-data, which is the "apache group"

`$ usermod -a -G www-data nginx`

**Comment by kennyparsons** [comment] 2020-12-29 02:54
Done, and restarted nginx for good measure, but still no luck. 
```bash
root@dal-prod-hosting01:~# members www-data
www-data nginx
```

**Comment by rail5** [comment] 2020-12-29 03:01
Let's try this

test-1.php:
```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

session_start();
$_SESSION['testvar'] = "1234";
var_dump($_SESSION);
?>
```

test-2.php:
```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

session_start();
var_dump($_SESSION);
?>
```

Run test-1.php then test-2.php and paste the output here

**Comment by kennyparsons** [comment] 2020-12-29 03:04
```bash
root@dal-prod-hosting01:~# php test1.php 
array(1) {
  ["testvar"]=>
  string(4) "1234"
}
```
```bash
root@dal-prod-hosting01:~# php test2.php 
array(0) {
}
```

**Comment by rail5** [comment] 2020-12-29 03:08
I mean, all that's clear from this is that the problem is fundamentally with the configuration of your server, and that your php-fpm and nginx are failing to store and retrieve session data. I'd love to help, but I don't have access to your server, and you're in a much better position to troubleshoot that than anyone else is.

At any rate, as this is an issue with your server rather than with SimpleFS, I'm closing this thread

**Closed by rail5** 2020-12-29 03:08 UTC

**Comment by kennyparsons** [comment] 2020-12-29 03:11
Would you mind posting a recommended nginx config? I get that it might be how it's implemented, but if people don't know how it should be implemented properly, it's all guess work.

**Comment by kennyparsons** [comment] 2020-12-29 03:16
Or perhaps share the required php functions required.

**Comment by rail5** [comment] 2020-12-29 03:18
Well, I'm not entirely convinced that nginx has heaps to do with the problem (though it may), as you ran php in the terminal as root and it still failed to store & retrieve the data -- I've never encountered that before; sessions are a very ordinary part of php which don't require special configuration

My immediate thoughts are:
1. What hosting service are you using? Maybe there's something strange about it
2. Maybe a clue would be given in the error logs of PHP & Nginx
3. And I'd still be generally inclined to think it has to do with directory permissions somehow

**Comment by kennyparsons** [comment] 2020-12-29 18:09
1. Self-Hosted Debian 10
2. Error logs for php only show the form submissions. No actual errors. Nginx log is below
```
2020/12/29 07:54:26 [error] 22910#22910: *683 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: submitted in /srv/www/fs-techup-dev/login.php on line 6" while reading response header from upstream, client: 192.168.2.231, server: 127.0.0.1, request: "GET /login.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.2.16:11001", referrer: "http://192.168.2.16:11001/login.php"
```
3. Here is a copy of my php.ini: https://gist.github.com/kennyparsons/ca9951ff5080b9184a9b0e8629b1c45a
As far as I can tell, here are all the directories php will touch:
`/srv/www/`
`/var/lib/php/tmp_upload`
`/var/lib/php/sessions`
`/var/lib/php/soap_cache`
`/var/log/php/

All five directories, including sub-dirs are owned by www-data:www-data (`/var/lib/php/` is owned by root).
