### ISSUE TITLE
Still now not working copy link area.

### ISSUE THREAD

**Issue by techandtips86** [rail5/SimpleFS#9] opened 2023-04-28 06:03 UTC
Still now not working copy link area.

**Comment by rail5** [comment] 2023-04-28 06:09
What browser are you using? It's working on all of the browsers I've tested

**Comment by techandtips86** [comment] 2023-04-28 06:25
In my office I am using Mac, Chrome and Safari. Both are facing the same
issue.

**Comment by techandtips86** [comment] 2023-04-28 06:30
i make a video but not uploaded cause of size.

**Comment by rail5** [comment] 2023-04-28 06:50
I've tested on both **Safari 16.4.1** and **Google Chrome 111.0.5563.146** (latest versions) on MacOS, and both the "Copy Link" button & selecting/copying from the text field are working perfectly in my tests

Closing as "can't reproduce"

**Closed as not planned by rail5** 2023-04-28 06:50 UTC

**Comment by techandtips86** [comment] 2023-04-28 07:53
After clear catch it is working.
